[workspace]
resolver = "3"
members = ["crates/feff10-sys", "crates/feff10", "crates/feff10-cli"]
exclude = ["crates/feff10-python"]

[workspace.package]
edition = "2024"
version = "0.1.6"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ameyanagi/feff10-rs"
homepage = "https://github.com/Ameyanagi/feff10-rs"
readme = "README.md"
keywords = ["feff", "xas", "exafs", "xanes", "spectroscopy"]
categories = ["science"]
